version: 2
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: mvn clean test
      - run:
          name: Save test results
          command: |
            mkdir -p test-results/junit/
            cp target/surefire-reports/*.xml test-results/junit
            ls -l ~/test-results/junit/
          when: always
      - store_test_results:
            path: ~/test-results
